### ISSUE TITLE
[BUG] Invalid app manifest format

### ISSUE THREAD

**Issue by NathanHRich** [slackapi/deno-slack-hooks#63]
### Describe the bug
After adding more workflows, `slack manifest validate` returns a generic "Invalid app manifest format:" error. Commenting out any large workflow resolves the issue.
See this forum post for more info and screenshots: https://forums.slackcommunity.com/s/question/0D73a000006itwbCAA/detail
cc: @filmaj 

### Requirements (place an `x` in each of the `[ ]`)**
* [ x ] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [ x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x ] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce
Unsure. I presume, keep adding workflows and custom functions to your app until you get this error.

### Expected behavior
The server should respond that the manifest is valid

#### Screenshots
See community post: https://forums.slackcommunity.com/s/question/0D73a000006itwbCAA/detail

**Comment by filmaj** [comment]
Thanks for filing the issue and following me over here from the forums 😄 

Could I get you to run the following from the app directory, and see if valid JSON was output?

```
deno run -q --config=deno.jsonc --allow-read --allow-net --allow-env https://deno.land/x/deno_slack_hooks@1.0.0/get_manifest.ts
```

**Comment by NathanHRich** [comment]
Yes, it returns a valid JSON object

**Comment by filmaj** [comment]
Whoa! I think you are a record holder, then 🥇 

One theory as to what might be going on... we recently released a new "protocol" between the CLI and the SDK - when you run `slack` CLI commands, this protocol is used under the hood. The new protocol uses a 'message boundary' message passing mechanism - delineating bits of the expected response of work delegation from the CLI to the SDK with these message boundaries - so that the SDK can report logging or diagnostic info and the CLI knows how to delineate those from the actual work delegation responses.

What if you run the `slack manifest` command on its own (without `validate`)? It should output the manifest JSON blob directly - do you see that?

In the mean time I will experiment locally with a similarly-sized manifest and see if I can reproduce.

**Comment by filmaj** [comment]
OK, one thing I did was I took the deno-github-functions sample and copied its workflow's first OpenForm step like, 100 times. The workflow file is now roughly ~275kb.

I noticed that if I now run `slack manifest`, the command doesn't finish 😬 
If, however, I run the underlying `deno` command that powers `slack manfiest` (in essence something like `deno run --config=deno.jsonc --allow-read --allow-net --allow-env https://deno.land/x/deno_slack_hooks@1.0.0/get_manifest.ts --source=/Users/fmaj/src/hungry-mule-668 --protocol=message-boundaries --boundary=4e626d656e766278466ad41d8cd98f00b204e9800998ecf8427e`), it executes and finishes immediately.

Do you get a similar issue?

**Comment by filmaj** [comment]
Can you try running this slightly-tweaked version of a `deno` command, that specifies to use the new message boundary protocol? You will have to adjust the `--source` flag to match the path to your app:

```
deno run --config=deno.jsonc --allow-read --allow-net --allow-env https://deno.land/x/deno_slack_hooks@1.0.0/get_manifest.ts --source=/Users/fmaj/src/hungry-mule-668 --protocol=message-boundaries --boundary=4e626d656e766278466ad41d8cd98f00b204e9800998ecf8427e
```

The expected output should be the `boundary` string at the start, a JSON blob of your entire app, and the `boundary` string at the end.

**Comment by filmaj** [comment]
OK. Good to know... how big of a JSON blob are we talking? Can you pipe that `deno run` command into `| wc -c` to get a byte count? Something like `deno run ... --boundary=12345 | wc -c`. Just so I'm in the same ballpark as I try to reproduce the invalid app manifest error you see.

**Comment by NathanHRich** [comment]
result of `wc -c`
`69109`

**Comment by filmaj** [comment]
Awesome! The one I created and was working with was 200,000+ bytes ... I dialed mine down now to ~67kb and now I can reproduce the error you see:

```
15:50:14 in ~/src/hungry-mule-668 via 🦕 v1.33.0
➜ deno run --config=deno.jsonc --allow-read --allow-net --allow-env https://deno.land/x/deno_slack_hooks@1.0.0/get_manifest.ts --source=/Users/fmaj/src/hungry-mule-668 --protocol=message-boundaries --boundary=4e626d656e766278466ad41d8cd98f00b204e9800998ecf8427e | wc -c
   67899

15:51:27 in ~/src/hungry-mule-668 via 🦕 v1.33.0
➜ slak manifest
Check /Users/fmaj/.slack/logs/slack-debug-20230428.log for full error logs

🚫 Invalid app manifest format:
```

Thank you for bearing with me 🙏 

Now I will dig in and start figuring out what about the interaction here between the CLI and the deno runtime is falling apart. I will keep posting comments here with my progress, but FYI, it is close to my end of day, so probably will not be able to make much progress here until next week.

**Comment by NathanHRich** [comment]
No worries. I won't be working on this till next week anyway. Enjoy your weekend. Thanks for hopping on this with me.

**Comment by filmaj** [comment]
One potential workaround that I just tested out, in case it helps unblock you temporarily: roll back to v1.20.0 of the CLI or earlier, which doesn't use the new-protocol shenanigans I described earlier. In my local app that I reproduced the issue, that was enough to unblock me.

**Comment by NathanHRich** [comment]
Right you are. I was able to get it to validate by rolling back to v1.20.0

**Comment by filmaj** [comment]
OK, that definitely narrows it down to the new protocol.

In any case, I will keep investigating. I will post updates here!

**Comment by filmaj** [comment]
Just to keep everyone in the loop: the slack CLI is built on golang, and the latest CLI version's message-boundary-based protocol relies on tokenization/splitting of (JSON) streams emitted from the deno-slack-sdk (via this repo, deno-slack-hooks). This splitting/tokenization is built on top of [golang's Scanner construct](https://pkg.go.dev/go/scanner).

Unfortunately it seems like this scanner thingo has trouble with large text streams. I will look into tweaking how the CLI parses this stream to see if I can simply increase the amount of buffered text it can handle. If that won't work, however, I think [this comment in the golang scanner's source](https://cs.opensource.google/go/go/+/refs/tags/go1.20.3:src/bufio/scan.go;l=24)(emphasis mine) might need pursuing:

> Scanning stops unrecoverably at EOF, the first I/O error, or _a token too_
> _large to fit in the buffer_. When a scan stops, the reader may have
> advanced arbitrarily far past the last token. _Programs that need more_
> _control over error handling or large tokens, or must run sequential scans_
> _on a reader, should use bufio.Reader instead_.

**Comment by filmaj** [comment]
Just a quick update: we have a fix in the works and in review on the CLI side. I think it is very likely the next release of the CLI should address this bug - but that probably won't be for a couple more weeks! Hopefully the previous version can tide you over in the mean-time.

**Comment by NathanHRich** [comment]
Sweet, thanks! I'll stay on 1.20.0 till then.
Are there best practices anywhere regarding scaling of Slack-hosted apps? When is it appropriate to create a new app vs adding a workflow to an existing app? We've got plenty more workflows planned and aren't sure which route to go.

**Comment by filmaj** [comment]
FYI the next release will contain a fix for this, or at least, will bump the buffer to a max of 256kb. It will also include much better error reporting (with a `token too long` error now being raised should the new 256kb max be hit) and even yielded a 20% performance boost 😄 
Once the new CLI version is out I will report back here and close this issue out.

**Comment by filmaj** [comment]
The expectation is the next CLI version will be available Thursday sometime, FYI, but once it is live I'll comment in here.

**Comment by filmaj** [comment]
> Are there best practices anywhere regarding scaling of Slack-hosted apps? When is it appropriate to create a new app vs adding a workflow to an existing app? We've got plenty more workflows planned and aren't sure which route to go.

Woops sorry @NathanHRich I totally missed this earlier!
No best practices in this area to date, but here are two things to consider when making this decision that come to mind:
1. There is a maximum of 100 workflows per app.
2. Each workflow will use the housing application's icon when rendering inside the Slack client

**Comment by filmaj** [comment]
Slack CLI 2.3.0 is live and that should fix this issue! I will close this but feel free to re-open if you still encounter the issue.
