### ISSUE TITLE
[FEATURE] slack deploy boolean flag to skip listing triggers

### ISSUE THREAD

**Issue by NathanHRich** [slackapi/deno-slack-hooks#68]
### Description

I don't need to list all of my triggers every time I run a `slack deploy`
In a slack app with a lot of triggers, it can take quite a long time to list all of the triggers associated with my app. This is especially annoying with the list call fails and completely blocks deployment. See [this issue](https://github.com/slackapi/deno-slack-sdk/issues/180)

In my opinion, triggers should not be listed by default when `slack deploy` is run.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by filmaj** [comment]
Hey @NathanHRich thanks for writing in!
This is already on our radar and we will most certainly be adding a flag to skip listing triggers to the slack CLI in the near future.

**Comment by filmaj** [comment]
Just an update here: this flag is on the docket for the upcoming release of the CLI slated for Thursday next week. I'll post again once that is live.
