### ISSUE TITLE
[BUG] Slack app can't be deployed with npm packages

### ISSUE THREAD

**Issue by higebu** [slackapi/deno-slack-hooks#70]
### Describe the bug

Slack app can't be deployed with npm packages, because `deno bundle` doesn't support npm packages and `deno bundle` has been deprecated(https://docs.deno.com/runtime/manual/tools/bundler). Please use [deno_emit](https://deno.land/x/emit@0.29.0) instead of `deno bundle`.

### Requirements (place an `x` in each of the `[ ]`)**
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce

1. Import a npm package like this: `import OpenAI from 'npm:openai';`
2. `slack deploy`

### Expected behavior

Slack app should be deployed with npm packages.

#### Screenshots

```
⠼ Packaging app for deploymenterror: npm specifiers have not yet been implemented for this subcommand (https://github.com/denoland/deno/issues/15960). Found: npm:/openai@4.12.1
⠴ Packaging app for deploymentError bundling function file: translate
error: Uncaught (in promise) Error: Error bundling function file: translate
throw new Error(`Error bundling function file: ${fnId}`);
            ^
at createFunctionFile (https://deno.land/x/deno_slack_hooks@1.1.0/build.ts:82:13)
at eventLoopTick (ext:core/01_core.js:183:11)
at async validateAndCreateFunctions (https://deno.land/x/deno_slack_hooks@1.1.0/build.ts:39:5)
at async https://deno.land/x/deno_slack_hooks@1.1.0/build.ts:127:3
Check /home/user/.slack/logs/slack-debug-20231018.log for full error logs

🚫 error packaging project: Command for 'BuildProject' returned an error: exit status 1 (sdk_hook_invocation_failed)
```

#### Reproducible in:

Deno version: v1.37.2
Slack CLI version: v2.10.0

**Comment by filmaj** [comment]
As a workaround, you can use a npm via a CDN like esm.sh as described in https://docs.deno.com/runtime/manual/node/cdns

**Comment by higebu** [comment]
@filmaj Thank you!

**Comment by higebu** [comment]
Closed by https://github.com/slackapi/deno-slack-hooks/pull/71
Thank you!
